-- Canonical Carbon Tracker schema. C# queries use users.user_name (not username).
CREATE TABLE IF NOT EXISTS users (user_id UUID PRIMARY KEY DEFAULT uuidv4(), user_name TEXT UNIQUE NOT NULL CHECK (LENGTH(user_name) <= 20), email TEXT UNIQUE NOT NULL, first_name TEXT CHECK (LENGTH(first_name) <= 20), password_hash TEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS password_reset_tokens (token TEXT PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(user_id), expires_at TIMESTAMP NOT NULL, used_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS refresh_tokens (token TEXT PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(user_id), expires_at TIMESTAMP NOT NULL, revoked_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS houses (house_id UUID PRIMARY KEY DEFAULT uuidv4(), user_id UUID REFERENCES users(user_id), energy_label TEXT, size_m2 INTEGER, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS items (item_id UUID PRIMARY KEY DEFAULT uuidv4(), user_id UUID REFERENCES users(user_id), item_name TEXT NOT NULL CHECK (LENGTH(item_name) <= 50), date_of_purchase DATE, use_case TEXT CHECK (LENGTH(use_case) <= 20), price NUMERIC(10, 2), footprint_kg NUMERIC(10, 3), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS commutes (commute_id UUID PRIMARY KEY DEFAULT uuidv4(), user_id UUID REFERENCES users(user_id), mode TEXT, distance_km_per_trip NUMERIC(10, 3), times_per_week INTEGER, work_from_home_days_per_week INTEGER, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS questionnaire (id UUID PRIMARY KEY, canonical_id UUID NOT NULL, version INTEGER NOT NULL, title TEXT NOT NULL, definition_json TEXT NOT NULL, status TEXT NOT NULL CHECK (status IN ('draft', 'active', 'inactive')), supersedes_id UUID, replaced_by_id UUID, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE (canonical_id, version));
CREATE TABLE IF NOT EXISTS response (id UUID PRIMARY KEY, questionnaire_id UUID NOT NULL REFERENCES questionnaire(id), canonical_id UUID NOT NULL, user_id UUID, submitted_at TIMESTAMP NOT NULL, definition_hash TEXT, answers_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS response_item (id UUID PRIMARY KEY, response_id UUID NOT NULL REFERENCES response(id), question_id TEXT NOT NULL, answer_text TEXT, answer_numeric DECIMAL(18, 4), answer_choice_id TEXT);
CREATE INDEX IF NOT EXISTS idx_response_questionnaire ON response(questionnaire_id);
CREATE INDEX IF NOT EXISTS idx_response_canonical ON response(canonical_id);
CREATE INDEX IF NOT EXISTS idx_response_item_question ON response_item(question_id);
